### ISSUE TITLE
microPEM accelerometer data

### ISSUE THREAD

**Issue by wangjingke** [ropensci-archive/rtimicropem#1]
Hi Maëlle,

have you thought about using data from the microPEM built-in accelerometer data? I understand that the accelerometer measurements were presented as +/- g on triaxial directions. Can they be converted to activity summary counts similar to the output produced by the Actigraph? Or can they be used to determine wear/non-wear of the device?

Thanks,
Jing

**Comment by maelle** [comment]
Hi Jing,

We only used them for checking participant compliance (we used the accelerometer values to see whether the device had been worn), but for now we've not used them a lot. But I need to ask my colleagues in India how they did it, then I'll tell you!

**Comment by maelle** [comment]
PS: But I would rather implement analysis methods in a separate package / use existing packages, just show an example in a vignette how to export the corresponding columns and how to analyse them. :-)

**Comment by wangjingke** [comment]
Thanks for the quick response. Could you please tell me your algorithms for defining nonwear? We tried the 0.007 g cutoff, but have a hard time distinguish nonwear from very sedentary positions like sitting in office or classroom.

**Comment by maelle** [comment]
So actually it's only visual inspection in our study: "Compliance checks are all visual comparing the accelerometer report (pdf) with the activity log and comments from the participants  and sometimes checks by calling the participant to verify the activity. "

Well this is for field work but for analysis, maybe we'll do something more. Do you discuss wearing compliance with participants? What is your study?

I must add that in our study, we also have other devices (an autographer that takes pictures, and a GPS).

**Comment by wangjingke** [comment]
Thanks for the clarification. I am part of the MADRES study (http://madrescenter.blogspot.com/). It is still at pilot stage, but we are trying to figure out a way to determine wear/nonwear of the microPEM. We ask the participants for compliance, but we also want a confirmation from the accelerometer.

**Comment by maelle** [comment]
Ok, thanks for the link, @wangjingke ! It sounds like an interesting study!

How are you analyzing the data? If you use the package I promise much help in exchange for user reports -> please tell me whether you find it useful and how we can improve it! It's a work in progress. :construction_worker:
