### ISSUE TITLE
Suggestions for the Shiny app

### ISSUE THREAD

**Issue by johneyyang** [ropensci-archive/rtimicropem#28]

**Comment by johneyyang** [comment]
Even the same newest version, depending on the user's settings, the output format might be different. I think the Shiny App needs to note this. 

I did not know this but was working on a shiny app with very similar functions, I will upload soon.

**Comment by maelle** [comment]
Thank you! Do you have a file you could send me as an example? I used two versions of files.

**Comment by johneyyang** [comment]
Hi Maelle,

This is a file from a deployment in China by China CDC. Can you please keep
it confidential and delete it after you download it for App development?
Thank you.

-Qiang


Qiang (Johnny) Yang, Ph.D
Associate Research Scientist
Lamont-Doherty Earth Observatory of Columbia University
Comer Building Room 437
61 Route 9W, Palisades, NY 10964
Phone: 1-845-365-8629
qyang@ldeo.columbia.edu

**Comment by maelle** [comment]
Send it at Maelle.salmon at yahoo.se and I'll handle it  confidentially. It wasn't uploaded with your comment.  Thanks a Lot! And also can you tell me which version of the device it is?

**Comment by maelle** [comment]
@johneyyang Thanks for sending me both files via email. I've found the problem, your files had a date format that I hadn't encountered yet in MicroPEM files. Now the app should work, could you install the latest version of the package and tell me if this solves your issue?

For information I'll soon upload the package to CRAN.

Thanks again for reporting the issue.

**Comment by maelle** [comment]
oh and I forgot to say that if you want to add your app _in_ this package, you're welcome to do it via a Pull Request.

**Comment by maelle** [comment]
In this case I'd add you to the list of contributors of course.

**Comment by johneyyang** [comment]
Hi Maelle,

Thanks for addressing my issues. Yes, the new app works. But I find a
couple more issues:

1) in the interactive plots, the last plot shows the accelorometer data
x-axis but in the plain plots the last is battery. I am not sure if you
intend to show this way. Also in the interactive plots, variable names
sometimes get cut off.

2) I mostly use plotly::subplot to make interactive plots, which has an
advantage that when you zoom in on any one of the plots, all the others
zoom into the same x-axis scale. I am not familiar with Rbokeh, not sure if
you can add the same function, but I think it might be helpful for viewing
microPEM data in details.

3) file size: I think you did not set the upload file size to >5 MB. Again
I am not sure if you intend to be this way to keep the ShinyApp running
smoothly, but in many applications the raw data files could be larger than
5 MB.


Best,

Qiang


Qiang (Johnny) Yang, Ph.D
Associate Research Scientist
Lamont-Doherty Earth Observatory of Columbia University
Comer Building Room 437
61 Route 9W, Palisades, NY 10964
Phone: 1-845-365-8629
qyang@ldeo.columbia.edu

**Comment by maelle** [comment]
Great that it solved your problem and thanks for this useful feedback!
