### ISSUE TITLE
Reading MicroPEM output files in different platforms

### ISSUE THREAD

**Issue by maelle** [ropensci-archive/rtimicropem#3]
The issue is: MicroPEM output files I have are created on Windows. I have written code for reading them in Windows. It does not work in Linux (Travis CI).

**Comment by masalmon** [comment]
well not even sure this is the issue :-(

**Comment by masalmon** [comment]
or maybe the test is written in a weird way, new try

**Comment by maelle** [comment]
So the issue is that UNIX and DOS files have different end-of-lines.
Now I wonder if the software of MicroPEM only outputs DOS-like files.

What I need to do:
- find a way for the file reading to work even with a file created in Windows to be read in Linux
- check whether there exists files created in Linux... and how to deal with them.

**Comment by maelle** [comment]
For now I have the impression that the MicroPEM Docking Station Software only exists for Windows.

**Comment by dolugen** [comment]
Hi. Can you attach an example file?

**Comment by maelle** [comment]
Hi, thanks, Yes that's the file here https://github.com/masalmon/ammon/blob/master/inst/extdata/dummyColumbia.csv 

I'm gonna look at this here https://help.github.com/articles/dealing-with-line-endings/ and try change my git options, it might be a good solution.

**Comment by maelle** [comment]
I solved the issue by transforming the file using "tr -d '\r' < file-name > file-name-unix" in a shell from RStudio for both "Columbia" files, and now I use these files instead of the ones with \r\n.
